control_unit_node:
  ros__parameters:
    control_unit: "keyboard" # joy, esp8266, keyboard
    device_name: "/dev/ttyUSB0"

commander_node:
  ros__parameters:
    vehicle_dimensions:
   
      - 0.58   # Vehicle Width
      - 1.00   # Vehicle Length
      - 0.05   # Vehicle Height
#     - x      # Wheel Radius 
#     - x      # Vehicle Weight
    lidar_rules:
      - 3.00   # Max Range
      - 0.05   # Min Range

      # Sensor Location (relative to vehicle)
      - 0.48    # X
      - 0.0    # Y
      - 0.18    # Z

      # - 3.14   # Horizontal Max Angle
      # - -3.14  # Horizontal Min Angle
      # - 0.05   # Vertical Max Angle
      # - -0.05  # Vertical Min Angle
      # - 0.01   # Noise
      
/**:                      # Can be used for all nodes
  ros__parameters:
    max_angular_velocity: 0.75
    max_linear_velocity: 2.20

camera_node:
  ros__parameters:
    select_input: "simulation" # camera, simulation